version: "3.2"

# create default network
networks:
  default:
    name: my-network
    external: true

volumes:
  db_space:
           
services:

    db:
      image: mariadb
      container_name: lamp_mariadb
      restart: unless-stopped
      init: true
      volumes:
        - "db_space:/var/lib/mysql"
      environment:
        MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    adminer:
      image: adminer
      container_name: lamp_adminer
      restart: unless-stopped
      init: true
      depends_on:
          - db
      ports:
          - "8080:8080"

    # db:
    #     image: mysql
    #     container_name: lamp_db
    #     init: true
    #     restart: unless-stopped
    #     environment:
    #       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    #       MYSQL_DATABASE: ${MY_DATABASE}
    #       MYSQL_USER: ${MYSQL_USER}
    #       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    #     ports:
    #     - "9906:3306"

    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     container_name: lamp_phpmyadmin
    #     init: true
    #     restart: unless-stopped
    #     environment:
    #       PMA_HOST: db
    #     depends_on:
    #         - db
    #     ports:
    #         - "8080:80"

    php-apache:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: lamp_php_apache
      restart: unless-stopped
      init: true
      depends_on:
          - db
      volumes:
          - "./html:/var/www/html:rw"
      ports:
          - "80:80"
